[package]
name = "bevy_plugin_template"
version = "0.1.0"
edition = "2021"
readme = "README.md"
keywords = ["bevy", "plugin"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = "0.9.1"
bevy_core = "0.9.1"
bevy_ecs = "0.9.1"